module Evergreen.Migrate.V45 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V43.Api.Card
import Evergreen.V43.Api.Data
import Evergreen.V43.Api.User
import Evergreen.V43.Auth.Common
import Evergreen.V43.Gen.Model
import Evergreen.V43.Gen.Msg
import Evergreen.V43.Gen.Pages
import Evergreen.V43.Gen.Params.Login.Provider_.Callback
import Evergreen.V43.OAuth
import Evergreen.V43.OAuth.AuthorizationCode
import Evergreen.V43.Pages.Admin
import Evergreen.V43.Pages.Cards
import Evergreen.V43.Pages.Catalog
import Evergreen.V43.Pages.Home_
import Evergreen.V43.Pages.Login
import Evergreen.V43.Pages.Login.Provider_.Callback
import Evergreen.V43.Pages.NotFound
import Evergreen.V43.Pages.Study
import Evergreen.V43.Render.Msg
import Evergreen.V43.Scripta.API
import Evergreen.V43.Shared
import Evergreen.V43.Types
import Evergreen.V45.Api.Card
import Evergreen.V45.Api.Data
import Evergreen.V45.Api.User
import Evergreen.V45.Auth.Common
import Evergreen.V45.Gen.Model
import Evergreen.V45.Gen.Msg
import Evergreen.V45.Gen.Pages
import Evergreen.V45.Gen.Params.Login.Provider_.Callback
import Evergreen.V45.OAuth
import Evergreen.V45.OAuth.AuthorizationCode
import Evergreen.V45.Pages.Admin
import Evergreen.V45.Pages.Cards
import Evergreen.V45.Pages.Catalog
import Evergreen.V45.Pages.Home_
import Evergreen.V45.Pages.Login
import Evergreen.V45.Pages.Login.Provider_.Callback
import Evergreen.V45.Pages.NotFound
import Evergreen.V45.Pages.Study
import Evergreen.V45.Render.Msg
import Evergreen.V45.Scripta.API
import Evergreen.V45.Shared
import Evergreen.V45.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V43.Types.FrontendModel -> ModelMigration Evergreen.V45.Types.FrontendModel Evergreen.V45.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V43.Types.BackendModel -> ModelMigration Evergreen.V45.Types.BackendModel Evergreen.V45.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V43.Types.FrontendMsg -> MsgMigration Evergreen.V45.Types.FrontendMsg Evergreen.V45.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V43.Types.ToBackend -> MsgMigration Evergreen.V45.Types.ToBackend Evergreen.V45.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V43.Types.BackendMsg -> MsgMigration Evergreen.V45.Types.BackendMsg Evergreen.V45.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V43.Types.ToFrontend -> MsgMigration Evergreen.V45.Types.ToFrontend Evergreen.V45.Types.FrontendMsg
toFrontend old =
    MsgOldValueIgnored
