module Evergreen.Migrate.V48 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V45.Auth.Common
import Evergreen.V45.OAuth
import Evergreen.V45.OAuth.AuthorizationCode
import Evergreen.V45.Types
import Evergreen.V48.Auth.Common
import Evergreen.V48.OAuth
import Evergreen.V48.OAuth.AuthorizationCode
import Evergreen.V48.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V45.Types.FrontendModel -> ModelMigration Evergreen.V48.Types.FrontendModel Evergreen.V48.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V45.Types.BackendModel -> ModelMigration Evergreen.V48.Types.BackendModel Evergreen.V48.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V45.Types.FrontendMsg -> MsgMigration Evergreen.V48.Types.FrontendMsg Evergreen.V48.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V45.Types.ToBackend -> MsgMigration Evergreen.V48.Types.ToBackend Evergreen.V48.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V45.Types.BackendMsg -> MsgMigration Evergreen.V48.Types.BackendMsg Evergreen.V48.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V45.Types.ToFrontend -> MsgMigration Evergreen.V48.Types.ToFrontend Evergreen.V48.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Auth_Common_AuthChallengeReason : Evergreen.V45.Auth.Common.AuthChallengeReason -> Evergreen.V48.Auth.Common.AuthChallengeReason
migrate_Auth_Common_AuthChallengeReason old =
    case old of
        Evergreen.V45.Auth.Common.AuthSessionMissing ->
            Evergreen.V48.Auth.Common.AuthSessionMissing

        Evergreen.V45.Auth.Common.AuthSessionInvalid ->
            Evergreen.V48.Auth.Common.AuthSessionInvalid

        Evergreen.V45.Auth.Common.AuthSessionExpired ->
            Evergreen.V48.Auth.Common.AuthSessionExpired

        Evergreen.V45.Auth.Common.AuthSessionLoggedOut ->
            Evergreen.V48.Auth.Common.AuthSessionLoggedOut


migrate_Auth_Common_BackendMsg : Evergreen.V45.Auth.Common.BackendMsg -> Evergreen.V48.Auth.Common.BackendMsg
migrate_Auth_Common_BackendMsg old =
    case old of
        Evergreen.V45.Auth.Common.AuthSigninInitiated_ p0 ->
            Evergreen.V48.Auth.Common.AuthSigninInitiated_ p0

        Evergreen.V45.Auth.Common.AuthSigninInitiatedDelayed_ p0 p1 ->
            Evergreen.V48.Auth.Common.AuthSigninInitiatedDelayed_ p0 (p1 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V45.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6 ->
            Evergreen.V48.Auth.Common.AuthCallbackReceived_ p0 p1 p2 p3 p4 p5 p6

        Evergreen.V45.Auth.Common.AuthSuccess p0 p1 p2 p3 p4 ->
            Evergreen.V48.Auth.Common.AuthSuccess p0
                p1
                p2
                p3
                (p4 |> Result.mapError migrate_Auth_Common_Error >> Result.map (Tuple.mapBoth migrate_Auth_Common_UserInfo (Maybe.map migrate_Auth_Common_Token)))

        Evergreen.V45.Auth.Common.AuthRenewSession p0 p1 ->
            Evergreen.V48.Auth.Common.AuthRenewSession p0 p1


migrate_Auth_Common_Error : Evergreen.V45.Auth.Common.Error -> Evergreen.V48.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V45.Auth.Common.ErrStateMismatch ->
            Evergreen.V48.Auth.Common.ErrStateMismatch

        Evergreen.V45.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V48.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V45.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V48.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V45.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V48.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V45.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V48.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V45.Auth.Common.ErrAuthString p0 ->
            Evergreen.V48.Auth.Common.ErrAuthString p0


migrate_Auth_Common_ToFrontend : Evergreen.V45.Auth.Common.ToFrontend -> Evergreen.V48.Auth.Common.ToFrontend
migrate_Auth_Common_ToFrontend old =
    case old of
        Evergreen.V45.Auth.Common.AuthInitiateSignin p0 ->
            Evergreen.V48.Auth.Common.AuthInitiateSignin p0

        Evergreen.V45.Auth.Common.AuthError p0 ->
            Evergreen.V48.Auth.Common.AuthError (p0 |> migrate_Auth_Common_Error)

        Evergreen.V45.Auth.Common.AuthSessionChallenge p0 ->
            Evergreen.V48.Auth.Common.AuthSessionChallenge (p0 |> migrate_Auth_Common_AuthChallengeReason)


migrate_Auth_Common_Token : Evergreen.V45.Auth.Common.Token -> Evergreen.V48.Auth.Common.Token
migrate_Auth_Common_Token old =
    { methodId = old.methodId
    , token = old.token |> migrate_OAuth_Token
    , created = old.created
    , expires = old.expires
    }


migrate_Auth_Common_UserInfo : Evergreen.V45.Auth.Common.UserInfo -> Evergreen.V48.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V45.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V48.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V45.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V48.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V45.OAuth.ErrorCode -> Evergreen.V48.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V45.OAuth.InvalidRequest ->
            Evergreen.V48.OAuth.InvalidRequest

        Evergreen.V45.OAuth.UnauthorizedClient ->
            Evergreen.V48.OAuth.UnauthorizedClient

        Evergreen.V45.OAuth.AccessDenied ->
            Evergreen.V48.OAuth.AccessDenied

        Evergreen.V45.OAuth.UnsupportedResponseType ->
            Evergreen.V48.OAuth.UnsupportedResponseType

        Evergreen.V45.OAuth.InvalidScope ->
            Evergreen.V48.OAuth.InvalidScope

        Evergreen.V45.OAuth.ServerError ->
            Evergreen.V48.OAuth.ServerError

        Evergreen.V45.OAuth.TemporarilyUnavailable ->
            Evergreen.V48.OAuth.TemporarilyUnavailable

        Evergreen.V45.OAuth.Custom p0 ->
            Evergreen.V48.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V45.OAuth.Token -> Evergreen.V48.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V45.OAuth.Bearer p0 ->
            Evergreen.V48.OAuth.Bearer p0


migrate_Types_BackendMsg : Evergreen.V45.Types.BackendMsg -> Evergreen.V48.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V45.Types.AuthBackendMsg p0 ->
            Evergreen.V48.Types.AuthBackendMsg (p0 |> migrate_Auth_Common_BackendMsg)

        Evergreen.V45.Types.CheckSession p0 p1 ->
            Evergreen.V48.Types.CheckSession p0 p1

        Evergreen.V45.Types.RenewSession p0 p1 p2 p3 ->
            Evergreen.V48.Types.RenewSession p0 p1 p2 p3

        Evergreen.V45.Types.NoOpBackendMsg ->
            Evergreen.V48.Types.EVERGREEN_NOOP

        Evergreen.V45.Types.Tick p0 ->
            Evergreen.V48.Types.Tick p0
