module Evergreen.Migrate.V50 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V49.Api.Card
import Evergreen.V49.Api.Data
import Evergreen.V49.Api.User
import Evergreen.V49.Auth.Common
import Evergreen.V49.Bridge
import Evergreen.V49.Gen.Model
import Evergreen.V49.Gen.Msg
import Evergreen.V49.Gen.Pages
import Evergreen.V49.Gen.Params.Login.Provider_.Callback
import Evergreen.V49.OAuth
import Evergreen.V49.OAuth.AuthorizationCode
import Evergreen.V49.Pages.Admin
import Evergreen.V49.Pages.Cards
import Evergreen.V49.Pages.Catalog
import Evergreen.V49.Pages.Home_
import Evergreen.V49.Pages.Login
import Evergreen.V49.Pages.Login.Provider_.Callback
import Evergreen.V49.Pages.NotFound
import Evergreen.V49.Pages.Stories.KatexDemo
import Evergreen.V49.Pages.Study
import Evergreen.V49.Render.Msg
import Evergreen.V49.Scripta.API
import Evergreen.V49.Shared
import Evergreen.V49.Types
import Evergreen.V50.Api.Card
import Evergreen.V50.Api.Data
import Evergreen.V50.Api.User
import Evergreen.V50.Auth.Common
import Evergreen.V50.Bridge
import Evergreen.V50.Gen.Model
import Evergreen.V50.Gen.Msg
import Evergreen.V50.Gen.Pages
import Evergreen.V50.Gen.Params.Login.Provider_.Callback
import Evergreen.V50.OAuth
import Evergreen.V50.OAuth.AuthorizationCode
import Evergreen.V50.Pages.Admin
import Evergreen.V50.Pages.Cards
import Evergreen.V50.Pages.Catalog
import Evergreen.V50.Pages.Home_
import Evergreen.V50.Pages.Login
import Evergreen.V50.Pages.Login.Provider_.Callback
import Evergreen.V50.Pages.NotFound
import Evergreen.V50.Pages.Stories.KatexDemo
import Evergreen.V50.Pages.Study
import Evergreen.V50.Render.Msg
import Evergreen.V50.Scripta.API
import Evergreen.V50.Shared
import Evergreen.V50.Types
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V49.Types.FrontendModel -> ModelMigration Evergreen.V50.Types.FrontendModel Evergreen.V50.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V49.Types.BackendModel -> ModelMigration Evergreen.V50.Types.BackendModel Evergreen.V50.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V49.Types.FrontendMsg -> MsgMigration Evergreen.V50.Types.FrontendMsg Evergreen.V50.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V49.Types.ToBackend -> MsgMigration Evergreen.V50.Types.ToBackend Evergreen.V50.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V49.Types.BackendMsg -> MsgMigration Evergreen.V50.Types.BackendMsg Evergreen.V50.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V49.Types.ToFrontend -> MsgMigration Evergreen.V50.Types.ToFrontend Evergreen.V50.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V49.Types.BackendModel -> Evergreen.V50.Types.BackendModel
migrate_Types_BackendModel old =
    { sessions = old.sessions
    , users = old.users
    , cards = old.cards |> Dict.map (\k -> migrate_Api_Card_CardEnvelope)
    , now = old.now
    , seed = old.seed
    , nextCardId = old.nextCardId
    , pendingAuths = old.pendingAuths
    }


migrate_Types_FrontendModel : Evergreen.V49.Types.FrontendModel -> Evergreen.V50.Types.FrontendModel
migrate_Types_FrontendModel old =
    { url = old.url
    , key = old.key
    , shared = old.shared |> migrate_Shared_Model
    , page = old.page |> migrate_Gen_Pages_Model
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    }


migrate_Types_ToBackend : Evergreen.V49.Types.ToBackend -> Evergreen.V50.Types.ToBackend
migrate_Types_ToBackend old =
    old |> migrate_Bridge_ToBackend


migrate_Api_Card_CardEnvelope : Evergreen.V49.Api.Card.CardEnvelope -> Evergreen.V50.Api.Card.CardEnvelope
migrate_Api_Card_CardEnvelope old =
    { id = old.id
    , card = old.card |> migrate_Api_Card_FlashCard
    , userId = old.userId
    , createdAt = old.createdAt
    , lastModifiedOn = old.lastModifiedOn
    , nextPromptSchedFor = old.nextPromptSchedFor
    , frequency = old.frequency |> migrate_Api_Card_PromptFrequency
    }


migrate_Api_Card_FlashCard : Evergreen.V49.Api.Card.FlashCard -> Evergreen.V50.Api.Card.FlashCard
migrate_Api_Card_FlashCard old =
    case old of
        Evergreen.V49.Api.Card.PlainText p0 ->
            Evergreen.V50.Api.Card.Markdown
                { question = p0.question
                , answer = p0.answer
                , tag = Nothing
                }

        Evergreen.V49.Api.Card.Markdown p0 ->
            Evergreen.V50.Api.Card.Markdown (p0 |> migrate_Api_Card_MarkdownCard)


migrate_Api_Card_Grade : Evergreen.V49.Api.Card.Grade -> Evergreen.V50.Api.Card.Grade
migrate_Api_Card_Grade old =
    case old of
        Evergreen.V49.Api.Card.Correct ->
            Evergreen.V50.Api.Card.Correct

        Evergreen.V49.Api.Card.Incorrect ->
            Evergreen.V50.Api.Card.Incorrect


migrate_Api_Card_MarkdownCard : Evergreen.V49.Api.Card.MarkdownCard -> Evergreen.V50.Api.Card.MarkdownCard
migrate_Api_Card_MarkdownCard old =
    old


migrate_Api_Card_PromptFrequency : Evergreen.V49.Api.Card.PromptFrequency -> Evergreen.V50.Api.Card.PromptFrequency
migrate_Api_Card_PromptFrequency old =
    case old of
        Evergreen.V49.Api.Card.Immediately ->
            Evergreen.V50.Api.Card.Immediately

        Evergreen.V49.Api.Card.OneDay ->
            Evergreen.V50.Api.Card.OneDay

        Evergreen.V49.Api.Card.TwoDays ->
            Evergreen.V50.Api.Card.TwoDays

        Evergreen.V49.Api.Card.SevenDays ->
            Evergreen.V50.Api.Card.SevenDays

        Evergreen.V49.Api.Card.FourteenDays ->
            Evergreen.V50.Api.Card.FourteenDays

        Evergreen.V49.Api.Card.ThirtyDays ->
            Evergreen.V50.Api.Card.ThirtyDays


migrate_Api_Card_StudySessionSummary : Evergreen.V49.Api.Card.StudySessionSummary -> Evergreen.V50.Api.Card.StudySessionSummary
migrate_Api_Card_StudySessionSummary old =
    old


migrate_Api_Data_Data : (value_old -> value_new) -> Evergreen.V49.Api.Data.Data value_old -> Evergreen.V50.Api.Data.Data value_new
migrate_Api_Data_Data migrate_value old =
    case old of
        Evergreen.V49.Api.Data.NotAsked ->
            Evergreen.V50.Api.Data.NotAsked

        Evergreen.V49.Api.Data.Loading ->
            Evergreen.V50.Api.Data.Loading

        Evergreen.V49.Api.Data.Failure p0 ->
            Evergreen.V50.Api.Data.Failure p0

        Evergreen.V49.Api.Data.Success p0 ->
            Evergreen.V50.Api.Data.Success (p0 |> migrate_value)


migrate_Api_User_User : Evergreen.V49.Api.User.User -> Evergreen.V50.Api.User.User
migrate_Api_User_User old =
    old


migrate_Auth_Common_AuthChallengeReason : Evergreen.V49.Auth.Common.AuthChallengeReason -> Evergreen.V50.Auth.Common.AuthChallengeReason
migrate_Auth_Common_AuthChallengeReason old =
    case old of
        Evergreen.V49.Auth.Common.AuthSessionMissing ->
            Evergreen.V50.Auth.Common.AuthSessionMissing

        Evergreen.V49.Auth.Common.AuthSessionInvalid ->
            Evergreen.V50.Auth.Common.AuthSessionInvalid

        Evergreen.V49.Auth.Common.AuthSessionExpired ->
            Evergreen.V50.Auth.Common.AuthSessionExpired

        Evergreen.V49.Auth.Common.AuthSessionLoggedOut ->
            Evergreen.V50.Auth.Common.AuthSessionLoggedOut


migrate_Auth_Common_Error : Evergreen.V49.Auth.Common.Error -> Evergreen.V50.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V49.Auth.Common.ErrStateMismatch ->
            Evergreen.V50.Auth.Common.ErrStateMismatch

        Evergreen.V49.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V50.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V49.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V50.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V49.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V50.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V49.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V50.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V49.Auth.Common.ErrAuthString p0 ->
            Evergreen.V50.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V49.Auth.Common.Flow -> Evergreen.V50.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V49.Auth.Common.Idle ->
            Evergreen.V50.Auth.Common.Idle

        Evergreen.V49.Auth.Common.Requested p0 ->
            Evergreen.V50.Auth.Common.Requested p0

        Evergreen.V49.Auth.Common.Pending ->
            Evergreen.V50.Auth.Common.Pending

        Evergreen.V49.Auth.Common.Authorized p0 p1 ->
            Evergreen.V50.Auth.Common.Authorized p0 p1

        Evergreen.V49.Auth.Common.Authenticated p0 ->
            Evergreen.V50.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V49.Auth.Common.Done p0 ->
            Evergreen.V50.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V49.Auth.Common.Errored p0 ->
            Evergreen.V50.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_ToBackend : Evergreen.V49.Auth.Common.ToBackend -> Evergreen.V50.Auth.Common.ToBackend
migrate_Auth_Common_ToBackend old =
    case old of
        Evergreen.V49.Auth.Common.AuthSigninInitiated p0 ->
            Evergreen.V50.Auth.Common.AuthSigninInitiated p0

        Evergreen.V49.Auth.Common.AuthCallbackReceived p0 p1 p2 p3 ->
            Evergreen.V50.Auth.Common.AuthCallbackReceived p0 p1 p2 p3

        Evergreen.V49.Auth.Common.AuthRenewSessionRequested ->
            Evergreen.V50.Auth.Common.AuthRenewSessionRequested

        Evergreen.V49.Auth.Common.AuthLogoutRequested ->
            Evergreen.V50.Auth.Common.AuthLogoutRequested


migrate_Auth_Common_ToFrontend : Evergreen.V49.Auth.Common.ToFrontend -> Evergreen.V50.Auth.Common.ToFrontend
migrate_Auth_Common_ToFrontend old =
    case old of
        Evergreen.V49.Auth.Common.AuthInitiateSignin p0 ->
            Evergreen.V50.Auth.Common.AuthInitiateSignin p0

        Evergreen.V49.Auth.Common.AuthError p0 ->
            Evergreen.V50.Auth.Common.AuthError (p0 |> migrate_Auth_Common_Error)

        Evergreen.V49.Auth.Common.AuthSessionChallenge p0 ->
            Evergreen.V50.Auth.Common.AuthSessionChallenge (p0 |> migrate_Auth_Common_AuthChallengeReason)


migrate_Auth_Common_UserInfo : Evergreen.V49.Auth.Common.UserInfo -> Evergreen.V50.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Bridge_ToBackend : Evergreen.V49.Bridge.ToBackend -> Evergreen.V50.Bridge.ToBackend
migrate_Bridge_ToBackend old =
    case old of
        Evergreen.V49.Bridge.SignedOut p0 ->
            Evergreen.V50.Bridge.SignedOut (p0 |> migrate_Api_User_User)

        Evergreen.V49.Bridge.AuthToBackend p0 ->
            Evergreen.V50.Bridge.AuthToBackend (p0 |> migrate_Auth_Common_ToBackend)

        Evergreen.V49.Bridge.CreateCard_Cards p0 p1 ->
            Evergreen.V50.Bridge.CreateCard_Cards (p0 |> migrate_Api_Card_FlashCard) p1

        Evergreen.V49.Bridge.FetchAdminSummary p0 ->
            Evergreen.V50.Bridge.FetchAdminSummary (p0 |> migrate_Api_User_User)

        Evergreen.V49.Bridge.FetchUsersStudyCards_Study p0 ->
            Evergreen.V50.Bridge.FetchUsersStudyCards_Study (p0 |> migrate_Api_User_User)

        Evergreen.V49.Bridge.FetchUsersStudySummary_Study p0 ->
            Evergreen.V50.Bridge.FetchUsersStudySummary_Study (p0 |> migrate_Api_User_User)

        Evergreen.V49.Bridge.UserSubmitGrade_Study p0 p1 ->
            Evergreen.V50.Bridge.UserSubmitGrade_Study p0 (p1 |> migrate_Api_Card_Grade)

        Evergreen.V49.Bridge.FetchUsersCatalog_Catalog p0 ->
            Evergreen.V50.Bridge.FetchUsersCatalog_Catalog (p0 |> migrate_Api_User_User)

        Evergreen.V49.Bridge.DeleteCard_Catalog p0 p1 ->
            Evergreen.V50.Bridge.DeleteCard_Catalog p0 p1


migrate_Gen_Model_Model : Evergreen.V49.Gen.Model.Model -> Evergreen.V50.Gen.Model.Model
migrate_Gen_Model_Model old =
    case old of
        Evergreen.V49.Gen.Model.Redirecting_ ->
            Evergreen.V50.Gen.Model.Redirecting_

        Evergreen.V49.Gen.Model.Admin p0 p1 ->
            Evergreen.V50.Gen.Model.Admin p0 (p1 |> migrate_Pages_Admin_Model)

        Evergreen.V49.Gen.Model.Cards p0 p1 ->
            Evergreen.V50.Gen.Model.Cards p0 (p1 |> migrate_Pages_Cards_Model)

        Evergreen.V49.Gen.Model.Catalog p0 p1 ->
            Evergreen.V50.Gen.Model.Catalog p0 (p1 |> migrate_Pages_Catalog_Model)

        Evergreen.V49.Gen.Model.Home_ p0 p1 ->
            Evergreen.V50.Gen.Model.Home_ p0 (p1 |> migrate_Pages_Home__Model)

        Evergreen.V49.Gen.Model.Login p0 p1 ->
            Evergreen.V50.Gen.Model.Login p0 (p1 |> migrate_Pages_Login_Model)

        Evergreen.V49.Gen.Model.NotFound p0 p1 ->
            Evergreen.V50.Gen.Model.NotFound p0 (p1 |> migrate_Pages_NotFound_Model)

        Evergreen.V49.Gen.Model.Study p0 p1 ->
            Evergreen.V50.Gen.Model.Study p0 (p1 |> migrate_Pages_Study_Model)

        Evergreen.V49.Gen.Model.Login__Provider___Callback p0 p1 ->
            Evergreen.V50.Gen.Model.Login__Provider___Callback (p0 |> migrate_Gen_Params_Login_Provider__Callback_Params)
                (p1 |> migrate_Pages_Login_Provider__Callback_Model)

        Evergreen.V49.Gen.Model.Stories__KatexDemo p0 p1 ->
            Evergreen.V50.Gen.Model.Stories__KatexDemo p0 (p1 |> migrate_Pages_Stories_KatexDemo_Model)


migrate_Gen_Msg_Msg : Evergreen.V49.Gen.Msg.Msg -> Evergreen.V50.Gen.Msg.Msg
migrate_Gen_Msg_Msg old =
    case old of
        Evergreen.V49.Gen.Msg.Admin p0 ->
            Evergreen.V50.Gen.Msg.Admin (p0 |> migrate_Pages_Admin_Msg)

        Evergreen.V49.Gen.Msg.Cards p0 ->
            Evergreen.V50.Gen.Msg.Cards (p0 |> migrate_Pages_Cards_Msg)

        Evergreen.V49.Gen.Msg.Catalog p0 ->
            Evergreen.V50.Gen.Msg.Catalog (p0 |> migrate_Pages_Catalog_Msg)

        Evergreen.V49.Gen.Msg.Home_ p0 ->
            Evergreen.V50.Gen.Msg.Home_ (p0 |> migrate_Pages_Home__Msg)

        Evergreen.V49.Gen.Msg.Login p0 ->
            Evergreen.V50.Gen.Msg.Login (p0 |> migrate_Pages_Login_Msg)

        Evergreen.V49.Gen.Msg.NotFound p0 ->
            Evergreen.V50.Gen.Msg.NotFound (p0 |> migrate_Pages_NotFound_Msg)

        Evergreen.V49.Gen.Msg.Study p0 ->
            Evergreen.V50.Gen.Msg.Study (p0 |> migrate_Pages_Study_Msg)

        Evergreen.V49.Gen.Msg.Login__Provider___Callback p0 ->
            Evergreen.V50.Gen.Msg.Login__Provider___Callback (p0 |> migrate_Pages_Login_Provider__Callback_Msg)

        Evergreen.V49.Gen.Msg.Stories__KatexDemo p0 ->
            Evergreen.V50.Gen.Msg.Stories__KatexDemo (p0 |> migrate_Pages_Stories_KatexDemo_Msg)


migrate_Gen_Pages_Model : Evergreen.V49.Gen.Pages.Model -> Evergreen.V50.Gen.Pages.Model
migrate_Gen_Pages_Model old =
    old |> migrate_Gen_Model_Model


migrate_Gen_Pages_Msg : Evergreen.V49.Gen.Pages.Msg -> Evergreen.V50.Gen.Pages.Msg
migrate_Gen_Pages_Msg old =
    old |> migrate_Gen_Msg_Msg


migrate_Gen_Params_Login_Provider__Callback_Params : Evergreen.V49.Gen.Params.Login.Provider_.Callback.Params -> Evergreen.V50.Gen.Params.Login.Provider_.Callback.Params
migrate_Gen_Params_Login_Provider__Callback_Params old =
    old


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V49.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V50.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V49.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V50.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V49.OAuth.ErrorCode -> Evergreen.V50.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V49.OAuth.InvalidRequest ->
            Evergreen.V50.OAuth.InvalidRequest

        Evergreen.V49.OAuth.UnauthorizedClient ->
            Evergreen.V50.OAuth.UnauthorizedClient

        Evergreen.V49.OAuth.AccessDenied ->
            Evergreen.V50.OAuth.AccessDenied

        Evergreen.V49.OAuth.UnsupportedResponseType ->
            Evergreen.V50.OAuth.UnsupportedResponseType

        Evergreen.V49.OAuth.InvalidScope ->
            Evergreen.V50.OAuth.InvalidScope

        Evergreen.V49.OAuth.ServerError ->
            Evergreen.V50.OAuth.ServerError

        Evergreen.V49.OAuth.TemporarilyUnavailable ->
            Evergreen.V50.OAuth.TemporarilyUnavailable

        Evergreen.V49.OAuth.Custom p0 ->
            Evergreen.V50.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V49.OAuth.Token -> Evergreen.V50.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V49.OAuth.Bearer p0 ->
            Evergreen.V50.OAuth.Bearer p0


migrate_Pages_Admin_Model : Evergreen.V49.Pages.Admin.Model -> Evergreen.V50.Pages.Admin.Model
migrate_Pages_Admin_Model old =
    old


migrate_Pages_Admin_Msg : Evergreen.V49.Pages.Admin.Msg -> Evergreen.V50.Pages.Admin.Msg
migrate_Pages_Admin_Msg old =
    case old of
        Evergreen.V49.Pages.Admin.GotAdminSummary p0 ->
            Evergreen.V50.Pages.Admin.GotAdminSummary p0


migrate_Pages_Cards_EditorField : Evergreen.V49.Pages.Cards.EditorField -> Evergreen.V50.Pages.Cards.EditorField
migrate_Pages_Cards_EditorField old =
    case old of
        Evergreen.V49.Pages.Cards.PlainText_Question ->
            Evergreen.V50.Pages.Cards.Markdown_Question

        Evergreen.V49.Pages.Cards.PlainText_Answer ->
            Evergreen.V50.Pages.Cards.Markdown_Answer

        Evergreen.V49.Pages.Cards.Markdown_Question ->
            Evergreen.V50.Pages.Cards.Markdown_Question

        Evergreen.V49.Pages.Cards.Markdown_Answer ->
            Evergreen.V50.Pages.Cards.Markdown_Answer

        Evergreen.V49.Pages.Cards.Markdown_Tag ->
            Evergreen.V50.Pages.Cards.Markdown_Tag


migrate_Pages_Cards_EditorForm : Evergreen.V49.Pages.Cards.EditorForm -> Evergreen.V50.Pages.Cards.EditorForm
migrate_Pages_Cards_EditorForm old =
    case old of
        Evergreen.V49.Pages.Cards.PlainTextForm p0 ->
            Evergreen.V50.Pages.Cards.MarkdownForm
                { question = p0.question
                , answer = p0.answer
                , tag = Nothing
                }

        Evergreen.V49.Pages.Cards.MarkdownForm p0 ->
            Evergreen.V50.Pages.Cards.MarkdownForm (p0 |> migrate_Api_Card_MarkdownCard)


migrate_Pages_Cards_Model : Evergreen.V49.Pages.Cards.Model -> Evergreen.V50.Pages.Cards.Model
migrate_Pages_Cards_Model old =
    { selectedOption = old.selectedOption |> migrate_Pages_Cards_SelectedFormRadioOption
    , editorForm = old.editorForm |> migrate_Pages_Cards_EditorForm
    , cardSubmitStatus = old.cardSubmitStatus |> migrate_Api_Data_Data identity
    , user = old.user |> migrate_Api_User_User
    , count = old.count
    }


migrate_Pages_Cards_Msg : Evergreen.V49.Pages.Cards.Msg -> Evergreen.V50.Pages.Cards.Msg
migrate_Pages_Cards_Msg old =
    case old of
        Evergreen.V49.Pages.Cards.FormUpdated p0 p1 p2 ->
            Evergreen.V50.Pages.Cards.FormUpdated (p0 |> migrate_Pages_Cards_EditorForm)
                (p1 |> migrate_Pages_Cards_EditorField)
                p2

        Evergreen.V49.Pages.Cards.ToggledOption p0 ->
            Evergreen.V50.Pages.Cards.ToggledOption (p0 |> migrate_Pages_Cards_SelectedFormRadioOption)

        Evergreen.V49.Pages.Cards.Submitted p0 p1 ->
            Evergreen.V50.Pages.Cards.Submitted (p0 |> migrate_Api_Card_FlashCard) p1

        Evergreen.V49.Pages.Cards.GotCard p0 ->
            Evergreen.V50.Pages.Cards.GotCard (p0 |> migrate_Api_Data_Data identity)

        Evergreen.V49.Pages.Cards.Render p0 ->
            Evergreen.V50.Pages.Cards.Render (p0 |> migrate_Scripta_API_Msg)

        Evergreen.V49.Pages.Cards.Noop p0 ->
            Evergreen.V50.Pages.Cards.Noop p0


migrate_Pages_Cards_SelectedFormRadioOption : Evergreen.V49.Pages.Cards.SelectedFormRadioOption -> Evergreen.V50.Pages.Cards.SelectedFormRadioOption
migrate_Pages_Cards_SelectedFormRadioOption old =
    case old of
        Evergreen.V49.Pages.Cards.MarkdownRadioOption ->
            Evergreen.V50.Pages.Cards.MarkdownRadioOption

        Evergreen.V49.Pages.Cards.PlainTextRadioOption ->
            Evergreen.V50.Pages.Cards.MarkdownRadioOption


migrate_Pages_Catalog_Model : Evergreen.V49.Pages.Catalog.Model -> Evergreen.V50.Pages.Catalog.Model
migrate_Pages_Catalog_Model old =
    { user = old.user
    , zone = old.zone
    , wiredCards = old.wiredCards |> migrate_Api_Data_Data (List.map migrate_Api_Card_CardEnvelope)
    , selectedEnv = old.selectedEnv |> Maybe.map migrate_Api_Card_CardEnvelope
    , hoveredOnEnv = old.hoveredOnEnv |> Maybe.map migrate_Api_Card_CardEnvelope
    , deletedCardId = old.deletedCardId
    }


migrate_Pages_Catalog_Msg : Evergreen.V49.Pages.Catalog.Msg -> Evergreen.V50.Pages.Catalog.Msg
migrate_Pages_Catalog_Msg old =
    case old of
        Evergreen.V49.Pages.Catalog.FetchUserCatalog p0 ->
            Evergreen.V50.Pages.Catalog.FetchUserCatalog (p0 |> migrate_Api_User_User)

        Evergreen.V49.Pages.Catalog.GotUserCatalog p0 ->
            Evergreen.V50.Pages.Catalog.GotUserCatalog (p0 |> migrate_Api_Data_Data (List.map migrate_Api_Card_CardEnvelope))

        Evergreen.V49.Pages.Catalog.GotDeleteCardResponse p0 ->
            Evergreen.V50.Pages.Catalog.GotDeleteCardResponse p0

        Evergreen.V49.Pages.Catalog.UserSelectedCard p0 ->
            Evergreen.V50.Pages.Catalog.UserSelectedCard (p0 |> migrate_Api_Card_CardEnvelope)

        Evergreen.V49.Pages.Catalog.UserClickedDelete p0 p1 ->
            Evergreen.V50.Pages.Catalog.UserClickedDelete p0 p1

        Evergreen.V49.Pages.Catalog.UserMousesOver p0 ->
            Evergreen.V50.Pages.Catalog.UserMousesOver (p0 |> migrate_Api_Card_CardEnvelope)

        Evergreen.V49.Pages.Catalog.ClearTableHover ->
            Evergreen.V50.Pages.Catalog.ClearTableHover

        Evergreen.V49.Pages.Catalog.Render p0 ->
            Evergreen.V50.Pages.Catalog.Render (p0 |> migrate_Scripta_API_Msg)

        Evergreen.V49.Pages.Catalog.Noop ->
            Evergreen.V50.Pages.Catalog.Noop


migrate_Pages_Home__Model : Evergreen.V49.Pages.Home_.Model -> Evergreen.V50.Pages.Home_.Model
migrate_Pages_Home__Model old =
    { tab = old.tab |> migrate_Pages_Home__Tab
    }


migrate_Pages_Home__Msg : Evergreen.V49.Pages.Home_.Msg -> Evergreen.V50.Pages.Home_.Msg
migrate_Pages_Home__Msg old =
    case old of
        Evergreen.V49.Pages.Home_.Noop ->
            Evergreen.V50.Pages.Home_.Noop


migrate_Pages_Home__Tab : Evergreen.V49.Pages.Home_.Tab -> Evergreen.V50.Pages.Home_.Tab
migrate_Pages_Home__Tab old =
    case old of
        Evergreen.V49.Pages.Home_.Global ->
            Evergreen.V50.Pages.Home_.Global


migrate_Pages_Login_Model : Evergreen.V49.Pages.Login.Model -> Evergreen.V50.Pages.Login.Model
migrate_Pages_Login_Model old =
    { email = old.email
    , password = old.password
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    }


migrate_Pages_Login_Msg : Evergreen.V49.Pages.Login.Msg -> Evergreen.V50.Pages.Login.Msg
migrate_Pages_Login_Msg old =
    case old of
        Evergreen.V49.Pages.Login.GoogleOAuthSignInRequested ->
            Evergreen.V50.Pages.Login.GoogleOAuthSignInRequested

        Evergreen.V49.Pages.Login.GitHubOAuthSignInRequested ->
            Evergreen.V50.Pages.Login.GitHubOAuthSignInRequested

        Evergreen.V49.Pages.Login.GotUser p0 ->
            Evergreen.V50.Pages.Login.GotUser (p0 |> migrate_Api_Data_Data migrate_Api_User_User)


migrate_Pages_Login_Provider__Callback_Model : Evergreen.V49.Pages.Login.Provider_.Callback.Model -> Evergreen.V50.Pages.Login.Provider_.Callback.Model
migrate_Pages_Login_Provider__Callback_Model old =
    { authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    }


migrate_Pages_Login_Provider__Callback_Msg : Evergreen.V49.Pages.Login.Provider_.Callback.Msg -> Evergreen.V50.Pages.Login.Provider_.Callback.Msg
migrate_Pages_Login_Provider__Callback_Msg old =
    case old of
        Evergreen.V49.Pages.Login.Provider_.Callback.GotUser p0 ->
            Evergreen.V50.Pages.Login.Provider_.Callback.GotUser (p0 |> migrate_Api_Data_Data migrate_Api_User_User)


migrate_Pages_NotFound_Model : Evergreen.V49.Pages.NotFound.Model -> Evergreen.V50.Pages.NotFound.Model
migrate_Pages_NotFound_Model old =
    old


migrate_Pages_NotFound_Msg : Evergreen.V49.Pages.NotFound.Msg -> Evergreen.V50.Pages.NotFound.Msg
migrate_Pages_NotFound_Msg old =
    case old of
        Evergreen.V49.Pages.NotFound.ReplaceMe ->
            Evergreen.V50.Pages.NotFound.ReplaceMe


migrate_Pages_Stories_KatexDemo_Model : Evergreen.V49.Pages.Stories.KatexDemo.Model -> Evergreen.V50.Pages.Stories.KatexDemo.Model
migrate_Pages_Stories_KatexDemo_Model old =
    old


migrate_Pages_Stories_KatexDemo_Msg : Evergreen.V49.Pages.Stories.KatexDemo.Msg -> Evergreen.V50.Pages.Stories.KatexDemo.Msg
migrate_Pages_Stories_KatexDemo_Msg old =
    case old of
        Evergreen.V49.Pages.Stories.KatexDemo.Render p0 ->
            Evergreen.V50.Pages.Stories.KatexDemo.Render (p0 |> migrate_Scripta_API_Msg)


migrate_Pages_Study_Model : Evergreen.V49.Pages.Study.Model -> Evergreen.V50.Pages.Study.Model
migrate_Pages_Study_Model old =
    { cardDataFetch = old.cardDataFetch |> migrate_Api_Data_Data (List.map migrate_Api_Card_CardEnvelope)
    , promptStatus = old.promptStatus |> migrate_Pages_Study_PromptStatus
    , gradeSubmit = old.gradeSubmit |> migrate_Api_Data_Data identity
    , sessionSummary = old.sessionSummary |> migrate_Api_Data_Data migrate_Api_Card_StudySessionSummary
    , user = old.user
    }


migrate_Pages_Study_Msg : Evergreen.V49.Pages.Study.Msg -> Evergreen.V50.Pages.Study.Msg
migrate_Pages_Study_Msg old =
    case old of
        Evergreen.V49.Pages.Study.FetchCards p0 ->
            Evergreen.V50.Pages.Study.FetchCards (p0 |> migrate_Api_User_User)

        Evergreen.V49.Pages.Study.GotUserCards p0 ->
            Evergreen.V50.Pages.Study.GotUserCards (p0 |> migrate_Api_Data_Data (List.map migrate_Api_Card_CardEnvelope))

        Evergreen.V49.Pages.Study.UserClickedReveal ->
            Evergreen.V50.Pages.Study.UserClickedReveal

        Evergreen.V49.Pages.Study.UserSelfGrade p0 p1 ->
            Evergreen.V50.Pages.Study.UserSelfGrade p0 (p1 |> migrate_Api_Card_Grade)

        Evergreen.V49.Pages.Study.GotGradedResponse p0 ->
            Evergreen.V50.Pages.Study.GotGradedResponse (p0 |> migrate_Api_Data_Data identity)

        Evergreen.V49.Pages.Study.GotStudySessionSummary p0 ->
            Evergreen.V50.Pages.Study.GotStudySessionSummary (p0 |> migrate_Api_Data_Data migrate_Api_Card_StudySessionSummary)

        Evergreen.V49.Pages.Study.UserStartStudySession ->
            Evergreen.V50.Pages.Study.UserStartStudySession

        Evergreen.V49.Pages.Study.Render p0 ->
            Evergreen.V50.Pages.Study.Render (p0 |> migrate_Scripta_API_Msg)


migrate_Pages_Study_PromptStatus : Evergreen.V49.Pages.Study.PromptStatus -> Evergreen.V50.Pages.Study.PromptStatus
migrate_Pages_Study_PromptStatus old =
    case old of
        Evergreen.V49.Pages.Study.Idle ->
            Evergreen.V50.Pages.Study.Idle

        Evergreen.V49.Pages.Study.QuestionPrompted ->
            Evergreen.V50.Pages.Study.QuestionPrompted

        Evergreen.V49.Pages.Study.AnswerRevealed ->
            Evergreen.V50.Pages.Study.AnswerRevealed


migrate_Render_Msg_Handling : Evergreen.V49.Render.Msg.Handling -> Evergreen.V50.Render.Msg.Handling
migrate_Render_Msg_Handling old =
    case old of
        Evergreen.V49.Render.Msg.MHStandard ->
            Evergreen.V50.Render.Msg.MHStandard

        Evergreen.V49.Render.Msg.MHAsCheatSheet ->
            Evergreen.V50.Render.Msg.MHAsCheatSheet


migrate_Render_Msg_MarkupMsg : Evergreen.V49.Render.Msg.MarkupMsg -> Evergreen.V50.Render.Msg.MarkupMsg
migrate_Render_Msg_MarkupMsg old =
    case old of
        Evergreen.V49.Render.Msg.SendMeta p0 ->
            Evergreen.V50.Render.Msg.SendMeta p0

        Evergreen.V49.Render.Msg.SendLineNumber p0 ->
            Evergreen.V50.Render.Msg.SendLineNumber p0

        Evergreen.V49.Render.Msg.SelectId p0 ->
            Evergreen.V50.Render.Msg.SelectId p0

        Evergreen.V49.Render.Msg.HighlightId p0 ->
            Evergreen.V50.Render.Msg.HighlightId p0

        Evergreen.V49.Render.Msg.GetPublicDocument p0 p1 ->
            Evergreen.V50.Render.Msg.GetPublicDocument (p0 |> migrate_Render_Msg_Handling) p1

        Evergreen.V49.Render.Msg.GetPublicDocumentFromAuthor p0 p1 p2 ->
            Evergreen.V50.Render.Msg.GetPublicDocumentFromAuthor (p0 |> migrate_Render_Msg_Handling) p1 p2

        Evergreen.V49.Render.Msg.GetDocumentWithSlug p0 p1 ->
            Evergreen.V50.Render.Msg.GetDocumentWithSlug (p0 |> migrate_Render_Msg_Handling) p1

        Evergreen.V49.Render.Msg.ProposeSolution p0 ->
            Evergreen.V50.Render.Msg.ProposeSolution (p0 |> migrate_Render_Msg_SolutionState)


migrate_Render_Msg_SolutionState : Evergreen.V49.Render.Msg.SolutionState -> Evergreen.V50.Render.Msg.SolutionState
migrate_Render_Msg_SolutionState old =
    case old of
        Evergreen.V49.Render.Msg.Unsolved ->
            Evergreen.V50.Render.Msg.Unsolved

        Evergreen.V49.Render.Msg.Solved p0 ->
            Evergreen.V50.Render.Msg.Solved p0


migrate_Scripta_API_Msg : Evergreen.V49.Scripta.API.Msg -> Evergreen.V50.Scripta.API.Msg
migrate_Scripta_API_Msg old =
    old |> migrate_Render_Msg_MarkupMsg


migrate_Shared_Model : Evergreen.V49.Shared.Model -> Evergreen.V50.Shared.Model
migrate_Shared_Model old =
    old


migrate_Shared_Msg : Evergreen.V49.Shared.Msg -> Evergreen.V50.Shared.Msg
migrate_Shared_Msg old =
    case old of
        Evergreen.V49.Shared.ClickedSignOut ->
            Evergreen.V50.Shared.ClickedSignOut

        Evergreen.V49.Shared.SignedInUser p0 ->
            Evergreen.V50.Shared.SignedInUser (p0 |> migrate_Api_User_User)

        Evergreen.V49.Shared.SetTimeZoneToLocale p0 ->
            Evergreen.V50.Shared.SetTimeZoneToLocale p0


migrate_Types_FrontendMsg : Evergreen.V49.Types.FrontendMsg -> Evergreen.V50.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V49.Types.ChangedUrl p0 ->
            Evergreen.V50.Types.ChangedUrl p0

        Evergreen.V49.Types.ClickedLink p0 ->
            Evergreen.V50.Types.ClickedLink p0

        Evergreen.V49.Types.Shared p0 ->
            Evergreen.V50.Types.Shared (p0 |> migrate_Shared_Msg)

        Evergreen.V49.Types.Page p0 ->
            Evergreen.V50.Types.Page (p0 |> migrate_Gen_Pages_Msg)

        Evergreen.V49.Types.Noop ->
            Evergreen.V50.Types.Noop


migrate_Types_ToFrontend : Evergreen.V49.Types.ToFrontend -> Evergreen.V50.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V49.Types.AuthToFrontend p0 ->
            Evergreen.V50.Types.AuthToFrontend (p0 |> migrate_Auth_Common_ToFrontend)

        Evergreen.V49.Types.ActiveSession p0 ->
            Evergreen.V50.Types.ActiveSession (p0 |> migrate_Api_User_User)

        Evergreen.V49.Types.PageMsg p0 ->
            Evergreen.V50.Types.PageMsg (p0 |> migrate_Gen_Pages_Msg)

        Evergreen.V49.Types.NoOpToFrontend ->
            Evergreen.V50.Types.NoOpToFrontend
