module Evergreen.Migrate.V52 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V51.Api.Card
import Evergreen.V51.Api.User
import Evergreen.V51.Auth.Common
import Evergreen.V51.Bridge
import Evergreen.V51.OAuth
import Evergreen.V51.OAuth.AuthorizationCode
import Evergreen.V51.Types
import Evergreen.V52.Api.Card
import Evergreen.V52.Api.User
import Evergreen.V52.Auth.Common
import Evergreen.V52.Bridge
import Evergreen.V52.OAuth
import Evergreen.V52.OAuth.AuthorizationCode
import Evergreen.V52.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V51.Types.FrontendModel -> ModelMigration Evergreen.V52.Types.FrontendModel Evergreen.V52.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V51.Types.BackendModel -> ModelMigration Evergreen.V52.Types.BackendModel Evergreen.V52.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V51.Types.FrontendMsg -> MsgMigration Evergreen.V52.Types.FrontendMsg Evergreen.V52.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V51.Types.ToBackend -> MsgMigration Evergreen.V52.Types.ToBackend Evergreen.V52.Types.BackendMsg
toBackend old =
    MsgOldValueIgnored


backendMsg : Evergreen.V51.Types.BackendMsg -> MsgMigration Evergreen.V52.Types.BackendMsg Evergreen.V52.Types.BackendMsg
backendMsg old =
    MsgOldValueIgnored


toFrontend : Evergreen.V51.Types.ToFrontend -> MsgMigration Evergreen.V52.Types.ToFrontend Evergreen.V52.Types.FrontendMsg
toFrontend old =
    MsgUnchanged
