module Evergreen.Migrate.V55 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.com/docs/evergreen> for more info.

-}

import Evergreen.V54.Api.Card
import Evergreen.V54.Api.Data
import Evergreen.V54.Api.User
import Evergreen.V54.Auth.Common
import Evergreen.V54.Gen.Model
import Evergreen.V54.Gen.Pages
import Evergreen.V54.Gen.Params.Login.Provider_.Callback
import Evergreen.V54.OAuth
import Evergreen.V54.OAuth.AuthorizationCode
import Evergreen.V54.Pages.Admin
import Evergreen.V54.Pages.Cards
import Evergreen.V54.Pages.Catalog
import Evergreen.V54.Pages.Home_
import Evergreen.V54.Pages.Login
import Evergreen.V54.Pages.Login.Provider_.Callback
import Evergreen.V54.Pages.NotFound
import Evergreen.V54.Pages.Stories.KatexDemo
import Evergreen.V54.Pages.Stories.VellumTesting
import Evergreen.V54.Pages.Study
import Evergreen.V54.Shared
import Evergreen.V54.Types
import Evergreen.V54.VellumClient
import Evergreen.V55.Api.Card
import Evergreen.V55.Api.Data
import Evergreen.V55.Api.User
import Evergreen.V55.Auth.Common
import Evergreen.V55.Gen.Model
import Evergreen.V55.Gen.Pages
import Evergreen.V55.Gen.Params.Login.Provider_.Callback
import Evergreen.V55.OAuth
import Evergreen.V55.OAuth.AuthorizationCode
import Evergreen.V55.Pages.Admin
import Evergreen.V55.Pages.Cards
import Evergreen.V55.Pages.Catalog
import Evergreen.V55.Pages.Home_
import Evergreen.V55.Pages.Login
import Evergreen.V55.Pages.Login.Provider_.Callback
import Evergreen.V55.Pages.NotFound
import Evergreen.V55.Pages.Stories.KatexDemo
import Evergreen.V55.Pages.Stories.VellumTesting
import Evergreen.V55.Pages.Study
import Evergreen.V55.Shared
import Evergreen.V55.Types
import Evergreen.V55.VellumClient
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V54.Types.FrontendModel -> ModelMigration Evergreen.V55.Types.FrontendModel Evergreen.V55.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V54.Types.BackendModel -> ModelMigration Evergreen.V55.Types.BackendModel Evergreen.V55.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V54.Types.FrontendMsg -> MsgMigration Evergreen.V55.Types.FrontendMsg Evergreen.V55.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V54.Types.ToBackend -> MsgMigration Evergreen.V55.Types.ToBackend Evergreen.V55.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V54.Types.BackendMsg -> MsgMigration Evergreen.V55.Types.BackendMsg Evergreen.V55.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V54.Types.ToFrontend -> MsgMigration Evergreen.V55.Types.ToFrontend Evergreen.V55.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V54.Types.FrontendModel -> Evergreen.V55.Types.FrontendModel
migrate_Types_FrontendModel old =
    { url = old.url
    , key = old.key
    , shared = old.shared |> migrate_Shared_Model
    , page = old.page |> migrate_Gen_Pages_Model
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    }


migrate_Api_Card_CardEnvelope : Evergreen.V54.Api.Card.CardEnvelope -> Evergreen.V55.Api.Card.CardEnvelope
migrate_Api_Card_CardEnvelope old =
    { id = old.id
    , card = old.card |> migrate_Api_Card_FlashCard
    , userId = old.userId
    , createdAt = old.createdAt
    , lastModifiedOn = old.lastModifiedOn
    , nextPromptSchedFor = old.nextPromptSchedFor
    , frequency = old.frequency |> migrate_Api_Card_PromptFrequency
    }


migrate_Api_Card_FlashCard : Evergreen.V54.Api.Card.FlashCard -> Evergreen.V55.Api.Card.FlashCard
migrate_Api_Card_FlashCard old =
    case old of
        Evergreen.V54.Api.Card.Markdown p0 ->
            Evergreen.V55.Api.Card.Markdown (p0 |> migrate_Api_Card_MarkdownCard)


migrate_Api_Card_MarkdownCard : Evergreen.V54.Api.Card.MarkdownCard -> Evergreen.V55.Api.Card.MarkdownCard
migrate_Api_Card_MarkdownCard old =
    old


migrate_Api_Card_PromptFrequency : Evergreen.V54.Api.Card.PromptFrequency -> Evergreen.V55.Api.Card.PromptFrequency
migrate_Api_Card_PromptFrequency old =
    case old of
        Evergreen.V54.Api.Card.Immediately ->
            Evergreen.V55.Api.Card.Immediately

        Evergreen.V54.Api.Card.OneDay ->
            Evergreen.V55.Api.Card.OneDay

        Evergreen.V54.Api.Card.TwoDays ->
            Evergreen.V55.Api.Card.TwoDays

        Evergreen.V54.Api.Card.SevenDays ->
            Evergreen.V55.Api.Card.SevenDays

        Evergreen.V54.Api.Card.FourteenDays ->
            Evergreen.V55.Api.Card.FourteenDays

        Evergreen.V54.Api.Card.ThirtyDays ->
            Evergreen.V55.Api.Card.ThirtyDays


migrate_Api_Card_StudySessionSummary : Evergreen.V54.Api.Card.StudySessionSummary -> Evergreen.V55.Api.Card.StudySessionSummary
migrate_Api_Card_StudySessionSummary old =
    old


migrate_Api_Data_Data : (value_old -> value_new) -> Evergreen.V54.Api.Data.Data value_old -> Evergreen.V55.Api.Data.Data value_new
migrate_Api_Data_Data migrate_value old =
    case old of
        Evergreen.V54.Api.Data.NotAsked ->
            Evergreen.V55.Api.Data.NotAsked

        Evergreen.V54.Api.Data.Loading ->
            Evergreen.V55.Api.Data.Loading

        Evergreen.V54.Api.Data.Failure p0 ->
            Evergreen.V55.Api.Data.Failure p0

        Evergreen.V54.Api.Data.Success p0 ->
            Evergreen.V55.Api.Data.Success (p0 |> migrate_value)


migrate_Api_User_User : Evergreen.V54.Api.User.User -> Evergreen.V55.Api.User.User
migrate_Api_User_User old =
    old


migrate_Auth_Common_Error : Evergreen.V54.Auth.Common.Error -> Evergreen.V55.Auth.Common.Error
migrate_Auth_Common_Error old =
    case old of
        Evergreen.V54.Auth.Common.ErrStateMismatch ->
            Evergreen.V55.Auth.Common.ErrStateMismatch

        Evergreen.V54.Auth.Common.ErrAuthorization p0 ->
            Evergreen.V55.Auth.Common.ErrAuthorization (p0 |> migrate_OAuth_AuthorizationCode_AuthorizationError)

        Evergreen.V54.Auth.Common.ErrAuthentication p0 ->
            Evergreen.V55.Auth.Common.ErrAuthentication (p0 |> migrate_OAuth_AuthorizationCode_AuthenticationError)

        Evergreen.V54.Auth.Common.ErrHTTPGetAccessToken ->
            Evergreen.V55.Auth.Common.ErrHTTPGetAccessToken

        Evergreen.V54.Auth.Common.ErrHTTPGetUserInfo ->
            Evergreen.V55.Auth.Common.ErrHTTPGetUserInfo

        Evergreen.V54.Auth.Common.ErrAuthString p0 ->
            Evergreen.V55.Auth.Common.ErrAuthString p0


migrate_Auth_Common_Flow : Evergreen.V54.Auth.Common.Flow -> Evergreen.V55.Auth.Common.Flow
migrate_Auth_Common_Flow old =
    case old of
        Evergreen.V54.Auth.Common.Idle ->
            Evergreen.V55.Auth.Common.Idle

        Evergreen.V54.Auth.Common.Requested p0 ->
            Evergreen.V55.Auth.Common.Requested p0

        Evergreen.V54.Auth.Common.Pending ->
            Evergreen.V55.Auth.Common.Pending

        Evergreen.V54.Auth.Common.Authorized p0 p1 ->
            Evergreen.V55.Auth.Common.Authorized p0 p1

        Evergreen.V54.Auth.Common.Authenticated p0 ->
            Evergreen.V55.Auth.Common.Authenticated (p0 |> migrate_OAuth_Token)

        Evergreen.V54.Auth.Common.Done p0 ->
            Evergreen.V55.Auth.Common.Done (p0 |> migrate_Auth_Common_UserInfo)

        Evergreen.V54.Auth.Common.Errored p0 ->
            Evergreen.V55.Auth.Common.Errored (p0 |> migrate_Auth_Common_Error)


migrate_Auth_Common_UserInfo : Evergreen.V54.Auth.Common.UserInfo -> Evergreen.V55.Auth.Common.UserInfo
migrate_Auth_Common_UserInfo old =
    old


migrate_Gen_Model_Model : Evergreen.V54.Gen.Model.Model -> Evergreen.V55.Gen.Model.Model
migrate_Gen_Model_Model old =
    case old of
        Evergreen.V54.Gen.Model.Redirecting_ ->
            Evergreen.V55.Gen.Model.Redirecting_

        Evergreen.V54.Gen.Model.Admin p0 p1 ->
            Evergreen.V55.Gen.Model.Admin p0 (p1 |> migrate_Pages_Admin_Model)

        Evergreen.V54.Gen.Model.Cards p0 p1 ->
            Evergreen.V55.Gen.Model.Cards p0 (p1 |> migrate_Pages_Cards_Model)

        Evergreen.V54.Gen.Model.Catalog p0 p1 ->
            Evergreen.V55.Gen.Model.Catalog p0 (p1 |> migrate_Pages_Catalog_Model)

        Evergreen.V54.Gen.Model.Home_ p0 p1 ->
            Evergreen.V55.Gen.Model.Home_ p0 (p1 |> migrate_Pages_Home__Model)

        Evergreen.V54.Gen.Model.Login p0 p1 ->
            Evergreen.V55.Gen.Model.Login p0 (p1 |> migrate_Pages_Login_Model)

        Evergreen.V54.Gen.Model.NotFound p0 p1 ->
            Evergreen.V55.Gen.Model.NotFound p0 (p1 |> migrate_Pages_NotFound_Model)

        Evergreen.V54.Gen.Model.Study p0 p1 ->
            Evergreen.V55.Gen.Model.Study p0 (p1 |> migrate_Pages_Study_Model)

        Evergreen.V54.Gen.Model.Login__Provider___Callback p0 p1 ->
            Evergreen.V55.Gen.Model.Login__Provider___Callback (p0 |> migrate_Gen_Params_Login_Provider__Callback_Params)
                (p1 |> migrate_Pages_Login_Provider__Callback_Model)

        Evergreen.V54.Gen.Model.Stories__KatexDemo p0 p1 ->
            Evergreen.V55.Gen.Model.Stories__KatexDemo p0 (p1 |> migrate_Pages_Stories_KatexDemo_Model)

        Evergreen.V54.Gen.Model.Stories__VellumTesting p0 p1 ->
            Evergreen.V55.Gen.Model.Stories__VellumTesting p0
                (p1 |> migrate_Pages_Stories_VellumTesting_Model)


migrate_Gen_Pages_Model : Evergreen.V54.Gen.Pages.Model -> Evergreen.V55.Gen.Pages.Model
migrate_Gen_Pages_Model old =
    old |> migrate_Gen_Model_Model


migrate_Gen_Params_Login_Provider__Callback_Params : Evergreen.V54.Gen.Params.Login.Provider_.Callback.Params -> Evergreen.V55.Gen.Params.Login.Provider_.Callback.Params
migrate_Gen_Params_Login_Provider__Callback_Params old =
    old


migrate_OAuth_AuthorizationCode_AuthenticationError : Evergreen.V54.OAuth.AuthorizationCode.AuthenticationError -> Evergreen.V55.OAuth.AuthorizationCode.AuthenticationError
migrate_OAuth_AuthorizationCode_AuthenticationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    }


migrate_OAuth_AuthorizationCode_AuthorizationError : Evergreen.V54.OAuth.AuthorizationCode.AuthorizationError -> Evergreen.V55.OAuth.AuthorizationCode.AuthorizationError
migrate_OAuth_AuthorizationCode_AuthorizationError old =
    { error = old.error |> migrate_OAuth_ErrorCode
    , errorDescription = old.errorDescription
    , errorUri = old.errorUri
    , state = old.state
    }


migrate_OAuth_ErrorCode : Evergreen.V54.OAuth.ErrorCode -> Evergreen.V55.OAuth.ErrorCode
migrate_OAuth_ErrorCode old =
    case old of
        Evergreen.V54.OAuth.InvalidRequest ->
            Evergreen.V55.OAuth.InvalidRequest

        Evergreen.V54.OAuth.UnauthorizedClient ->
            Evergreen.V55.OAuth.UnauthorizedClient

        Evergreen.V54.OAuth.AccessDenied ->
            Evergreen.V55.OAuth.AccessDenied

        Evergreen.V54.OAuth.UnsupportedResponseType ->
            Evergreen.V55.OAuth.UnsupportedResponseType

        Evergreen.V54.OAuth.InvalidScope ->
            Evergreen.V55.OAuth.InvalidScope

        Evergreen.V54.OAuth.ServerError ->
            Evergreen.V55.OAuth.ServerError

        Evergreen.V54.OAuth.TemporarilyUnavailable ->
            Evergreen.V55.OAuth.TemporarilyUnavailable

        Evergreen.V54.OAuth.Custom p0 ->
            Evergreen.V55.OAuth.Custom p0


migrate_OAuth_Token : Evergreen.V54.OAuth.Token -> Evergreen.V55.OAuth.Token
migrate_OAuth_Token old =
    case old of
        Evergreen.V54.OAuth.Bearer p0 ->
            Evergreen.V55.OAuth.Bearer p0


migrate_Pages_Admin_Model : Evergreen.V54.Pages.Admin.Model -> Evergreen.V55.Pages.Admin.Model
migrate_Pages_Admin_Model old =
    old


migrate_Pages_Cards_EditorForm : Evergreen.V54.Pages.Cards.EditorForm -> Evergreen.V55.Pages.Cards.EditorForm
migrate_Pages_Cards_EditorForm old =
    case old of
        Evergreen.V54.Pages.Cards.MarkdownForm p0 ->
            Evergreen.V55.Pages.Cards.MarkdownForm (p0 |> migrate_Api_Card_MarkdownCard)

        Evergreen.V54.Pages.Cards.AiAssistedMarkdownForm p0 ->
            Evergreen.V55.Pages.Cards.AiAssistedMarkdownForm p0


migrate_Pages_Cards_Model : Evergreen.V54.Pages.Cards.Model -> Evergreen.V55.Pages.Cards.Model
migrate_Pages_Cards_Model old =
    { selectedOption = old.selectedOption |> migrate_Pages_Cards_SelectedFormRadioOption
    , editorForm = old.editorForm |> migrate_Pages_Cards_EditorForm
    , cardSubmitStatus = old.cardSubmitStatus |> migrate_Api_Data_Data identity
    , user = old.user |> migrate_Api_User_User
    , count = old.count
    }


migrate_Pages_Cards_SelectedFormRadioOption : Evergreen.V54.Pages.Cards.SelectedFormRadioOption -> Evergreen.V55.Pages.Cards.SelectedFormRadioOption
migrate_Pages_Cards_SelectedFormRadioOption old =
    case old of
        Evergreen.V54.Pages.Cards.MarkdownRadioOption ->
            Evergreen.V55.Pages.Cards.MarkdownRadioOption

        Evergreen.V54.Pages.Cards.AiAssistRadioOption ->
            Evergreen.V55.Pages.Cards.AiAssistRadioOption


migrate_Pages_Catalog_Model : Evergreen.V54.Pages.Catalog.Model -> Evergreen.V55.Pages.Catalog.Model
migrate_Pages_Catalog_Model old =
    { user = old.user
    , zone = old.zone
    , wiredCards = old.wiredCards |> migrate_Api_Data_Data (List.map migrate_Api_Card_CardEnvelope)
    , selectedEnv = old.selectedEnv |> Maybe.map migrate_Api_Card_CardEnvelope
    , hoveredOnEnv = old.hoveredOnEnv |> Maybe.map migrate_Api_Card_CardEnvelope
    , deletedCardId = old.deletedCardId
    }


migrate_Pages_Home__Model : Evergreen.V54.Pages.Home_.Model -> Evergreen.V55.Pages.Home_.Model
migrate_Pages_Home__Model old =
    { tab = old.tab |> migrate_Pages_Home__Tab
    }


migrate_Pages_Home__Tab : Evergreen.V54.Pages.Home_.Tab -> Evergreen.V55.Pages.Home_.Tab
migrate_Pages_Home__Tab old =
    case old of
        Evergreen.V54.Pages.Home_.Global ->
            Evergreen.V55.Pages.Home_.Global


migrate_Pages_Login_Model : Evergreen.V54.Pages.Login.Model -> Evergreen.V55.Pages.Login.Model
migrate_Pages_Login_Model old =
    { email = old.email
    , password = old.password
    , authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    }


migrate_Pages_Login_Provider__Callback_Model : Evergreen.V54.Pages.Login.Provider_.Callback.Model -> Evergreen.V55.Pages.Login.Provider_.Callback.Model
migrate_Pages_Login_Provider__Callback_Model old =
    { authFlow = old.authFlow |> migrate_Auth_Common_Flow
    , authRedirectBaseUrl = old.authRedirectBaseUrl
    }


migrate_Pages_NotFound_Model : Evergreen.V54.Pages.NotFound.Model -> Evergreen.V55.Pages.NotFound.Model
migrate_Pages_NotFound_Model old =
    old


migrate_Pages_Stories_KatexDemo_Model : Evergreen.V54.Pages.Stories.KatexDemo.Model -> Evergreen.V55.Pages.Stories.KatexDemo.Model
migrate_Pages_Stories_KatexDemo_Model old =
    old


migrate_Pages_Stories_VellumTesting_Model : Evergreen.V54.Pages.Stories.VellumTesting.Model -> Evergreen.V55.Pages.Stories.VellumTesting.Model
migrate_Pages_Stories_VellumTesting_Model old =
    { nCards = old.nCards
    , title = old.title
    , author = old.author
    , response = old.response |> migrate_VellumClient_RemoteData identity migrate_VellumClient_VellumResponse
    , vellumText = old.vellumText
    , vellumParsedCards = Nothing
    , pingResponse = old.pingResponse |> migrate_VellumClient_RemoteData identity migrate_VellumClient_PingResponse
    }


migrate_Pages_Study_Model : Evergreen.V54.Pages.Study.Model -> Evergreen.V55.Pages.Study.Model
migrate_Pages_Study_Model old =
    { cardDataFetch = old.cardDataFetch |> migrate_Api_Data_Data (List.map migrate_Api_Card_CardEnvelope)
    , promptStatus = old.promptStatus |> migrate_Pages_Study_PromptStatus
    , gradeSubmit = old.gradeSubmit |> migrate_Api_Data_Data identity
    , sessionSummary = old.sessionSummary |> migrate_Api_Data_Data migrate_Api_Card_StudySessionSummary
    , user = old.user
    }


migrate_Pages_Study_PromptStatus : Evergreen.V54.Pages.Study.PromptStatus -> Evergreen.V55.Pages.Study.PromptStatus
migrate_Pages_Study_PromptStatus old =
    case old of
        Evergreen.V54.Pages.Study.Idle ->
            Evergreen.V55.Pages.Study.Idle

        Evergreen.V54.Pages.Study.QuestionPrompted ->
            Evergreen.V55.Pages.Study.QuestionPrompted

        Evergreen.V54.Pages.Study.AnswerRevealed ->
            Evergreen.V55.Pages.Study.AnswerRevealed


migrate_Shared_Model : Evergreen.V54.Shared.Model -> Evergreen.V55.Shared.Model
migrate_Shared_Model old =
    old


migrate_VellumClient_PingResponse : Evergreen.V54.VellumClient.PingResponse -> Evergreen.V55.VellumClient.PingResponse
migrate_VellumClient_PingResponse old =
    old


migrate_VellumClient_RemoteData : (err_old -> err_new) -> (a_old -> a_new) -> Evergreen.V54.VellumClient.RemoteData err_old a_old -> Evergreen.V55.VellumClient.RemoteData err_new a_new
migrate_VellumClient_RemoteData migrate_err migrate_a old =
    case old of
        Evergreen.V54.VellumClient.NotAsked ->
            Evergreen.V55.VellumClient.NotAsked

        Evergreen.V54.VellumClient.Loading ->
            Evergreen.V55.VellumClient.Loading

        Evergreen.V54.VellumClient.Success p0 ->
            Evergreen.V55.VellumClient.Success (p0 |> migrate_a)

        Evergreen.V54.VellumClient.Failure p0 ->
            Evergreen.V55.VellumClient.Failure (p0 |> migrate_err)


migrate_VellumClient_VellumResponse : Evergreen.V54.VellumClient.VellumResponse -> Evergreen.V55.VellumClient.VellumResponse
migrate_VellumClient_VellumResponse old =
    old
